{
  "formatVersion": "1.1",
  "component": {
    "group": "me.xiaoying",
    "module": "sqlfactory",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "sqlfactory-1.3.0.jar",
          "url": "sqlfactory-1.3.0.jar",
          "size": 53318,
          "sha512": "74de5802d628d9882b84edb0c50a954288ef816c0ba4575be86eb1e3075daf22be5983dafd8c661463523074fceb80dfe9afbeafca67a5080a3d134f56bf7d57",
          "sha256": "9479e89f366d43e0a14cb00d015ebfc53c6d900ce612aa164cd1c2392b328b9c",
          "sha1": "5a710152968cac8c0610b821746ff63e4c4bbf0d",
          "md5": "2c6c67244076b340cc9582cf0254a05d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.xerial",
          "module": "sqlite-jdbc",
          "version": {
            "requires": "3.49.1.0"
          }
        },
        {
          "group": "com.mysql",
          "module": "mysql-connector-j",
          "version": {
            "requires": "9.5.0"
          }
        },
        {
          "group": "org.postgresql",
          "module": "postgresql",
          "version": {
            "requires": "42.7.8"
          }
        }
      ],
      "files": [
        {
          "name": "sqlfactory-1.3.0.jar",
          "url": "sqlfactory-1.3.0.jar",
          "size": 53318,
          "sha512": "74de5802d628d9882b84edb0c50a954288ef816c0ba4575be86eb1e3075daf22be5983dafd8c661463523074fceb80dfe9afbeafca67a5080a3d134f56bf7d57",
          "sha256": "9479e89f366d43e0a14cb00d015ebfc53c6d900ce612aa164cd1c2392b328b9c",
          "sha1": "5a710152968cac8c0610b821746ff63e4c4bbf0d",
          "md5": "2c6c67244076b340cc9582cf0254a05d"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sqlfactory-1.3.0-all.jar",
          "url": "sqlfactory-1.3.0-all.jar",
          "size": 20169277,
          "sha512": "bd33fe97cad938c5bfb1458d94a8269bf3b0b032b8ee84dbd6d29cc65396fef9cca6419f0b9078e1fd9424d3d9ef3efe923f09e787df4dc2fc56d82850f175fc",
          "sha256": "612ed635b723c7561804371d638a940aee549de35979a226b8b7643447513794",
          "sha1": "b9383bfbbcb756088197e8506367c9779c4e136c",
          "md5": "323a8757c4c23c5fe64e88513969cd2e"
        }
      ]
    }
  ]
}
