{
  "formatVersion": "1.1",
  "component": {
    "group": "me.xiaoying",
    "module": "sqlfactory",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "sqlfactory-1.3.0.jar",
          "url": "sqlfactory-1.3.0.jar",
          "size": 53280,
          "sha512": "46bd99238fa9d30f1e40a824f9b5c05017bc3d44b0c3ed1005fb0930aa15f0bc8092fef2b47cc17f1ad57618605668d9ea4faac7322ef16034059fdd870fb45e",
          "sha256": "fa4ac3e8900eb538fe019375cf19927cb830734432febd054b69b6e5cbf4ab22",
          "sha1": "a6013fce2a2b3e73337c874df32c213cc53e933d",
          "md5": "7ae7ee373a4a2e553f0bd320a77a81b8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.xerial",
          "module": "sqlite-jdbc",
          "version": {
            "requires": "3.49.1.0"
          }
        },
        {
          "group": "com.mysql",
          "module": "mysql-connector-j",
          "version": {
            "requires": "9.5.0"
          }
        },
        {
          "group": "org.postgresql",
          "module": "postgresql",
          "version": {
            "requires": "42.7.8"
          }
        }
      ],
      "files": [
        {
          "name": "sqlfactory-1.3.0.jar",
          "url": "sqlfactory-1.3.0.jar",
          "size": 53280,
          "sha512": "46bd99238fa9d30f1e40a824f9b5c05017bc3d44b0c3ed1005fb0930aa15f0bc8092fef2b47cc17f1ad57618605668d9ea4faac7322ef16034059fdd870fb45e",
          "sha256": "fa4ac3e8900eb538fe019375cf19927cb830734432febd054b69b6e5cbf4ab22",
          "sha1": "a6013fce2a2b3e73337c874df32c213cc53e933d",
          "md5": "7ae7ee373a4a2e553f0bd320a77a81b8"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sqlfactory-1.3.0-all.jar",
          "url": "sqlfactory-1.3.0-all.jar",
          "size": 20169239,
          "sha512": "f1962ab0d00ccd5231e4f68520b0d786d20b1197b0717d5b95f33ee3f78170977ce0dbb6407083ba0d3d4fb2cd819174565bd681f7da188e17065811511c410e",
          "sha256": "66d3ac215e897c6e826cb72bfd27b4ae832bbf9f6ea88bf81988465decbfefd4",
          "sha1": "fc501fe0aa3c58d00d21e3a17a2fc1a931a9f6a3",
          "md5": "d3b24b6bf4551cc399ec7835565a7596"
        }
      ]
    }
  ]
}
